#!/usr/bin/env node
// Starts a self-hosted Confer instance from published images.
//
// This runs under whatever Node the user's npx has, not under Bun, so nothing
// here may reach for a Bun API — only node: builtins and the docker CLI.

import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, realpathSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DEFAULT_PROJECT = 'confer';
const DEFAULT_PORT = 80;
const COMPOSE_FILE = 'docker-compose.ghcr.yml';

export type Command = 'up' | 'down' | 'logs' | 'help';

export type Options = {
  command: Command;
  port: number;
  dir: string;
  project: string;
  version: string;
};

export function defaults(): Omit<Options, 'command'> {
  return {
    port: DEFAULT_PORT,
    dir: join(homedir(), '.confer'),
    project: DEFAULT_PROJECT,
    version: 'latest',
  };
}

const FLAGS = ['port', 'dir', 'version', 'project'] as const;

export function parseArgs(argv: readonly string[]): Options | { error: string } {
  const positional: string[] = [];
  const flags = new Map<string, string>();
  const fallback = defaults();

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i] ?? '';
    if (!arg.startsWith('--')) {
      positional.push(arg);
      continue;
    }
    const [name = '', inline] = arg.slice(2).split('=', 2);
    if (name === 'help') return { command: 'help', ...fallback };
    // Silently ignoring a misspelled flag is worse than refusing it: `--prot
    // 8080` would start on port 80 and the mistake would surface as a puzzle.
    if (!FLAGS.includes(name as (typeof FLAGS)[number])) {
      return {
        error: `unknown option --${name} — expected ${FLAGS.map((f) => `--${f}`).join(', ')}`,
      };
    }
    const value = inline ?? argv[++i];
    if (value === undefined) return { error: `--${name} needs a value` };
    flags.set(name, value);
  }

  const command = (positional[0] ?? 'up') as Command;
  if (!['up', 'down', 'logs', 'help'].includes(command)) {
    return { error: `unknown command "${command}" — expected up, down or logs` };
  }

  const rawPort = flags.get('port') ?? String(fallback.port);
  const port = Number(rawPort);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    return { error: `--port must be a port number, got "${rawPort}"` };
  }

  return {
    command,
    port,
    dir: flags.get('dir') ?? fallback.dir,
    project: flags.get('project') ?? fallback.project,
    version: flags.get('version') ?? fallback.version,
  };
}

/** ENCRYPTION_KEY is read as 64 hex characters (32 bytes of AES-256-GCM key). */
export function generateSecrets(): { jwtSecret: string; encryptionKey: string } {
  return {
    jwtSecret: randomBytes(32).toString('hex'),
    encryptionKey: randomBytes(32).toString('hex'),
  };
}

export function renderEnvFile(vars: Record<string, string>): string {
  const body = Object.entries(vars)
    .map(([key, value]) => `${key}=${value}`)
    .join('\n');
  return `# Generated by confer-cli. Anyone who reads ENCRYPTION_KEY can decrypt
# every LLM key stored in this instance — keep this file to yourself.
${body}\n`;
}

const HELP = `confer — run a self-hosted Confer instance

  npx confer-cli              start it (pulls images, runs migrations)
  npx confer-cli down         stop it, keeping all data
  npx confer-cli logs         follow the gateway log

Options
  --port <n>       host port for the web UI (default ${DEFAULT_PORT})
  --dir <path>     where to keep config (default ~/.confer)
  --version <tag>  image tag to run (default latest)
  --project <name> docker compose project name (default ${DEFAULT_PROJECT})
`;

function run(command: string, args: readonly string[], cwd?: string, env?: NodeJS.ProcessEnv) {
  return spawnSync(command, args, { cwd, stdio: 'inherit', encoding: 'utf8', env });
}

function capture(command: string, args: readonly string[]) {
  return spawnSync(command, args, { encoding: 'utf8' });
}

function fail(message: string): never {
  process.stderr.write(`\nconfer: ${message}\n`);
  process.exit(1);
}

function preflight(): void {
  if (capture('docker', ['--version']).status !== 0) {
    fail('Docker is not installed. Get it at https://docs.docker.com/get-docker/');
  }
  if (capture('docker', ['info']).status !== 0) {
    fail('Docker is installed but not running. Start Docker Desktop (or dockerd) and retry.');
  }
  if (capture('docker', ['compose', 'version']).status !== 0) {
    fail('This needs Docker Compose v2 (the `docker compose` subcommand).');
  }
}

/**
 * Refuse to adopt a compose project we did not create. Volumes are keyed by
 * project name, so attaching to someone's existing `confer` stack would point
 * these images at their database and replace their running containers.
 */
function assertProjectIsOurs(project: string, composePath: string): void {
  if (existsSync(composePath)) return;
  // Fails open: this is a guard against an unlucky name collision, not a
  // security boundary, and a docker that cannot list projects should not be
  // the reason a first run refuses to start.
  const listed = capture('docker', ['compose', 'ls', '--all', '--format', 'json']);
  if (listed.status !== 0) return;
  let projects: Array<{ Name?: string }> = [];
  try {
    projects = JSON.parse(listed.stdout || '[]');
  } catch {
    return;
  }
  if (projects.some((entry) => entry.Name === project)) {
    fail(
      `a docker compose project named "${project}" already exists on this machine, ` +
        "and it was not created here. Its volumes hold someone else's data.\n" +
        '        Run with --project <other-name> to start a separate instance.',
    );
  }
}

async function waitForHealth(port: number, timeoutMs: number): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const response = await fetch(`http://127.0.0.1:${port}/health`);
      if (response.ok) return true;
    } catch {
      // not listening yet
    }
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
  return false;
}

function composeArgs(options: Options): string[] {
  return ['compose', '-p', options.project, '-f', COMPOSE_FILE];
}

/**
 * Every compose invocation gets the same values. Passing them to `up` but not
 * to `pull` would fetch one tag and start another.
 */
function composeEnv(options: Options): NodeJS.ProcessEnv {
  return {
    ...process.env,
    EXPOSE_PORT: String(options.port),
    CONFER_VERSION: options.version,
  };
}

async function up(options: Options): Promise<void> {
  preflight();

  const composePath = join(options.dir, COMPOSE_FILE);
  assertProjectIsOurs(options.project, composePath);
  // 0700: the only thing kept here is this instance's secrets.
  mkdirSync(options.dir, { recursive: true, mode: 0o700 });

  // Rewritten every run, so an upgrade picks up topology changes. Local edits
  // to this copy do not survive — change the compose file the CLI is not
  // managing if you need to customise it.
  const bundled = join(dirname(fileURLToPath(import.meta.url)), COMPOSE_FILE);
  if (!existsSync(bundled)) fail(`this install is missing ${COMPOSE_FILE} — reinstall confer-cli`);
  copyFileSync(bundled, composePath);

  const envPath = join(options.dir, '.env');
  if (!existsSync(envPath)) {
    const { jwtSecret, encryptionKey } = generateSecrets();
    writeFileSync(
      envPath,
      renderEnvFile({
        JWT_SECRET: jwtSecret,
        ENCRYPTION_KEY: encryptionKey,
        POSTGRES_PASSWORD: randomBytes(18).toString('hex'),
        MINIO_ROOT_PASSWORD: randomBytes(18).toString('hex'),
      }),
      { mode: 0o600 },
    );
    process.stdout.write(`Generated secrets in ${envPath}\n`);
  }

  const env = composeEnv(options);
  const diagnose = () =>
    run(
      'docker',
      [...composeArgs(options), 'logs', '--tail', '40', 'migrate', 'gateway'],
      options.dir,
      env,
    );

  // Not --quiet: this is the slow step (roughly a gigabyte on a cold machine),
  // and a rate-limited or stalled registry looks identical to a fast one when
  // the progress output is suppressed.
  process.stdout.write('Pulling images…\n');
  if (run('docker', [...composeArgs(options), 'pull'], options.dir, env).status !== 0) {
    fail('could not pull the images. Check your network, then retry.');
  }

  process.stdout.write('Starting…\n');
  if (run('docker', [...composeArgs(options), 'up', '-d'], options.dir, env).status !== 0) {
    diagnose();
    fail('the stack did not start. The logs above say why.');
  }

  // The success criterion is a served page, not a started container: the
  // gateway can be `running` and still be unable to resolve its dependencies.
  if (!(await waitForHealth(options.port, 180_000))) {
    diagnose();
    fail(`nothing answered on http://localhost:${options.port} within 3 minutes.`);
  }

  const url = options.port === 80 ? 'http://localhost' : `http://localhost:${options.port}`;
  process.stdout.write(
    `\n  Confer is running at ${url}\n` +
      '  Register the first account, then add an LLM API key in Settings.\n\n' +
      `  Stop it with:  npx confer-cli down${stopFlags(options)}\n\n`,
  );
}

/** Whatever the user has to repeat for `down` to find the same instance. */
export function stopFlags(options: Pick<Options, 'dir' | 'project'>): string {
  const fallback = defaults();
  return [
    options.dir === fallback.dir ? '' : ` --dir ${options.dir}`,
    options.project === fallback.project ? '' : ` --project ${options.project}`,
  ].join('');
}

export async function main(argv: readonly string[]): Promise<void> {
  const parsed = parseArgs(argv);
  if ('error' in parsed) fail(parsed.error);
  if (parsed.command === 'help') {
    process.stdout.write(HELP);
    return;
  }
  if (parsed.command === 'up') return up(parsed);

  preflight();
  // Without this, spawnSync fails on the missing cwd and reports nothing at all.
  if (!existsSync(join(parsed.dir, COMPOSE_FILE))) {
    fail(`no instance in ${parsed.dir}. Start one with \`npx confer-cli up\`.`);
  }
  const rest = parsed.command === 'down' ? ['down'] : ['logs', '-f', 'gateway'];
  const result = run('docker', [...composeArgs(parsed), ...rest], parsed.dir, composeEnv(parsed));
  if (result.status !== 0) process.exit(result.status ?? 1);
}

// `import.meta.main` is a Bun-ism; this has to work under plain Node too.
// argv[1] is the path as invoked, which for an npm-installed bin is the
// `node_modules/.bin/confer` symlink, while import.meta.url is already
// resolved to the real file. Comparing the two without realpath made every
// `npx confer-cli` a silent no-op that still exited 0 (shipped in 0.3.1).
const entry = process.argv[1];
if (entry && realpathSync(entry) === fileURLToPath(import.meta.url)) {
  await main(process.argv.slice(2));
}
